{:resource()->css([
'static/plugins/datatables/datatables.min.css',
'static/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'
])}


<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            {include file="message/message" /}
            <div class="portlet-body">
                {$actionRender | raw}
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                    <thead>
                    <tr>
                        <th>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                <span></span>
                            </label>
                        </th>
                        <th> 名称 </th>
                        <th> 所属权限 </th>
                        <th> 排序</th>
                        <th> 创建时间</th>
                        <th> 操作 </th>
                    </tr>
                    </thead>
                    <tbody>
                    {foreach $roleInfo as $role}
                    <tr class="odd gradeX">
                        <td>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input type="checkbox" class="checkboxes" value="1" />
                                <span></span>
                            </label>
                        </td>
                        <td class="center"> {:str_repeat('----',$role['level']).$role['name']}</td>
                        <td class="center">{:create_label_str($role['access_id'])}</td>
                        <td class="center"> {$role['sort']} </td>
                        <td class="center"> {$role['create_time'] | date="Y-m-d H:i:s"} </td>
                        <td>
                            {foreach $action as $val}
                            <div class="btn-group">
                                <a href="{:url($val['url'],['id'=>$role['id']])}" class="btn btn-outline {$val['style']}" > <i class="{$val['icon']}"></i> {$val['slug']}</a>
                            </div>
                            {/foreach}
                        </td>
                    </tr>
                    {/foreach}
                    </tbody>
                </table>

                <div class="box-footer clearfix">
                    <div class="col-md-7 col-sm-4">
                        <div class="dataTables_info" id="sample_1_info" role="status" aria-live="polite">
                            总共{$total}条记录
                        </div>
                    </div>
                    <div class="dataTables_paginate paging_bootstrap_full_number pull-right" id="sample_1_paginate">
                        {$pageRender |raw}
                    </div>
                </div>

                <div id="static2" class="modal fade"  style="top: 15%;" tabindex="-1" data-backdrop="static" data-keyboard="false" data-attention-animation="false">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">提示信息</h4>
                    </div>
                    <div class="modal-body">
                        <p class="grey-gallery"> 确认要删除该数据吗? </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn green mt-ladda-btn ladda-button btn-circle">取消</button>
                        <button type="button" data-dismiss="modal" class="btn purple mt-ladda-btn ladda-button btn-circle">确认</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{:resource()->js([
'static/js/global/datatable.js'
])}