
<!--<div class="row">-->
<!--    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">-->
<!--        <a class="dashboard-stat dashboard-stat-v2 blue" href="#">-->
<!--            <div class="visual">-->
<!--                <i class="fa fa-comments"></i>-->
<!--            </div>-->
<!--            <div class="details">-->
<!--                <div class="number">-->
<!--                    <span data-counter="counterup" data-value="1349">0</span>-->
<!--                </div>-->
<!--                <div class="desc"> New Feedbacks </div>-->
<!--            </div>-->
<!--        </a>-->
<!--    </div>-->
<!--    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">-->
<!--        <a class="dashboard-stat dashboard-stat-v2 red" href="#">-->
<!--            <div class="visual">-->
<!--                <i class="fa fa-bar-chart-o"></i>-->
<!--            </div>-->
<!--            <div class="details">-->
<!--                <div class="number">-->
<!--                    <span data-counter="counterup" data-value="12,5">0</span>M$ </div>-->
<!--                <div class="desc"> Total Profit </div>-->
<!--            </div>-->
<!--        </a>-->
<!--    </div>-->
<!--    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">-->
<!--        <a class="dashboard-stat dashboard-stat-v2 green" href="#">-->
<!--            <div class="visual">-->
<!--                <i class="fa fa-shopping-cart"></i>-->
<!--            </div>-->
<!--            <div class="details">-->
<!--                <div class="number">-->
<!--                    <span data-counter="counterup" data-value="549">0</span>-->
<!--                </div>-->
<!--                <div class="desc"> New Orders </div>-->
<!--            </div>-->
<!--        </a>-->
<!--    </div>-->
<!--    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">-->
<!--        <a class="dashboard-stat dashboard-stat-v2 purple" href="#">-->
<!--            <div class="visual">-->
<!--                <i class="fa fa-globe"></i>-->
<!--            </div>-->
<!--            <div class="details">-->
<!--                <div class="number"> +-->
<!--                    <span data-counter="counterup" data-value="89"></span>% </div>-->
<!--                <div class="desc"> Brand Popularity </div>-->
<!--            </div>-->
<!--        </a>-->
<!--    </div>-->
<!--</div>-->
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-social-dribbble font-green"></i>
                    <span class="caption-subject font-green bold uppercase">当前系统信息</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-scrollable">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th> 后台版本 </th>
                            <th> 操作系统 </th>
                            <th> 运行环境 </th>
                            <th> MYSQL版本 </th>
                            <th> PHP版本 </th>
                            <th> TP版本 </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td> {$data['auth_version']|default=''} </td>
                            <td> {$data['os']|default=''} </td>
                            <td> {$data['software']|default=''} </td>
                            <td> {$data['mysql_version']|default=''} </td>
                            <td> {$data['php_version']|default=''} </td>
                            <td> {$data['think_version']|default=''} </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>