<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <title>henry</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    {:resource()->css([
        'static/plugins/font-awesome/css/font-awesome.min.css',
        'static/plugins/simple-line-icons/simple-line-icons.min.css',
        'static/plugins/bootstrap/css/bootstrap.min.css',
        'static/plugins/bootstrap-select/css/bootstrap-select.min.css',
        'static/plugins/bootstrap-daterangepicker/daterangepicker.min.css',
        'static/css/global/components.min.css',
        'static/css/global/plugins.min.css',
        'static/common/layout/css/layout.min.css',
        'static/common/layout/css/themes/default.min.css',
        'static/common/layout/css/custom.min.css',
    ])}
    <!-- END HEAD -->
</head>