<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            {include file="message/message" /}
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="{:url('admin/menus/edit',['id'=>$menusInfo['id']])}" method="post" class="horizontal-form" pjax-container>
                    {:token()}
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">模块类型</label>
                                    <div class="md-radio-inline">
                                        <div class="md-radio">
                                            <input type="radio" id="menu_type0" value="0" name="menu_type" <?= $menusInfo['menu_type']==0 ? "checked" : ''; ?> class="md-radiobtn">
                                            <label for="menu_type0">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> 菜单导航 </label>
                                        </div>
                                        <div class="md-radio">
                                            <input type="radio" id="menu_type1" value="1" <?= $menusInfo['menu_type']==1 ? "checked" : ''; ?> name="menu_type" class="md-radiobtn menu_type">
                                            <label for="menu_type1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> 左部功能 </label>
                                        </div>
                                        <div class="md-radio">
                                            <input type="radio" id="menu_type2" value="2" <?= $menusInfo['menu_type']==2 ? "checked" : ''; ?> name="menu_type" class="md-radiobtn">
                                            <label for="menu_type2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> 特殊功能 </label>
                                        </div>
                                        <div class="md-radio">
                                            <input type="radio" id="menu_type3" value="3" <?= $menusInfo['menu_type']==3 ? "checked" : ''; ?> name="menu_type" class="md-radiobtn">
                                            <label for="menu_type3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span> 列表功能 </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">所属菜单</label>
                                    <select class="form-control" name="parent_id">
                                        <option value="0">顶级菜单</option>
                                        {foreach $nodes as $node}
                                        <option value="{$node['id']}" <?= $menusInfo['parent_id']==$node['id'] ? "selected" : ''; ?>>{:str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',$node['level']).$node['name']}</option>
                                        {/foreach}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">菜单导航头部</label>
                                    <input type="text" name="header" class="form-control" value="{$menusInfo['header']|default=''}" placeholder="菜单导航头部">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">图标</label>
                                    <input type="text" name="icon" value="{$menusInfo['icon']}" class="form-control icon iconpicker-element iconpicker-input" placeholder="icon"><a class="btn btn-sm dark" data-target="#full-width" data-toggle="modal"> 获取图标 </a>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label"><span class="required">*</span>  名称</label>
                                    <input type="text" name="name" value="{$menusInfo['name']}" class="form-control" placeholder="菜单名称">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">别名</label>
                                    <input type="text" name="slug" value="{$menusInfo['slug']}" class="form-control" placeholder="别名">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">url</label>
                                    <input type="text" name="url" value="{$menusInfo['url']}" class="form-control" placeholder="url">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">排序</label>
                                    <input type="text" name="sort" value="{$menusInfo['sort']}" class="form-control" placeholder="排序">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">样式</label>
                                    <input type="text" name="style" value="{$menusInfo['style']}" class="form-control" placeholder="样式 purple mt-ladda-btn btn-circle">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label">是否隐藏</label>
                                    <div class="md-checkbox">
                                        <input type="checkbox" value="1" id="status" <?= $menusInfo['status']==0 ? "checked" : ''; ?> name="status" class="md-check">
                                        <label for="status">
                                            <span></span>
                                            <span class="check"></span>
                                            <span class="box"></span> 是 </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="reset" class="btn yellow mt-ladda-btn ladda-button btn-circle">重置</button>
                        <button type="submit" data-loading-text="Loading..." class="btn purple mt-ladda-btn ladda-button mt-progress-demo btn-circle">
                            <i class="fa fa-check"></i> 保存</button>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>