{:resource()->css([
'static/plugins/datatables/datatables.min.css',
'static/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'
])}


<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            {include file="message/message" /}
            <div class="portlet-body">
                {$actionRender | raw}
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                    <thead>
                    <tr>
                        <th>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                <span></span>
                            </label>
                        </th>
                        <th> 名称 </th>
                        <th> 排序</th>
                        <th> url </th>
                        <th> 图标 </th>
                        <th> 状态 </th>
                        <th> 操作 </th>
                    </tr>
                    </thead>
                    <tbody>
                    {foreach $menusInfo as $menus}
                    <tr class="odd gradeX">
                        <td>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input type="checkbox" class="checkboxes" value="{$menus['id']}" />
                                <span></span>
                            </label>
                        </td>
                        <td class="center"> {$menus['name']}</td>
                        <td class="center">{$menus['sort']}</td>
                        <td class="center"> {$menus['url']} </td>
                        <td class="center"> {$menus['icon']} </td>
                        <td class="center"> {$menus['status']} </td>
                        <td>
                            {foreach $action as $val}
                            <div class="btn-group">
                                <a href="{:url($val['url'],['id'=>$menus['id']])}" class="btn btn-outline {$val['style']}" > <i class="{$val['icon']}"></i> {$val['slug']}</a>
                            </div>
                            {/foreach}
                        </td>
                    </tr>
                    {/foreach}
                    </tbody>
                </table>

                <div class="box-footer clearfix">
                    <div class="col-md-7 col-sm-4">
                        <div class="dataTables_info" id="sample_1_info" role="status" aria-live="polite">总共{$total|default=0}条
                        </div>
                    </div>
                    <div class="dataTables_paginate paging_bootstrap_full_number pull-right" id="sample_1_paginate">
                        {:$pageRender}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{:resource()->js([
'static/js/global/datatable.js'
])}